//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_BaseUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Db_BaseUser()
        {
            this.Db_BaseUserRole = new HashSet<Db_BaseUserRole>();
        }
    
        public string Id { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<System.DateTime> lastLoginTime { get; set; }
        public string lastLoginIpAddress { get; set; }
        public bool isDeleted { get; set; }
        public bool isDisabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_BaseUserRole> Db_BaseUserRole { get; set; }
    }
}
