//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_BaseWorkOrderTaskUser
    {
        public string Id { get; set; }
        public string Db_BaseWorkOrderId { get; set; }
        public string Db_WorkFlowDefinitionId { get; set; }
        public string Db_WorkFlowDefLineId { get; set; }
        public string Db_WorkFlowDefStepId { get; set; }
        public string UserId { get; set; }
        public string userName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsConfirm { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string Remark { get; set; }
    
        public virtual Db_BaseWorkOrder Db_BaseWorkOrder { get; set; }
    }
}
