//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_BaseUserRole
    {
        public string Id { get; set; }
        public string roleName { get; set; }
        public string Db_BaseUserId { get; set; }
    
        public virtual Db_BaseUser Db_BaseUser { get; set; }
    }
}
