//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_BaseWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Db_BaseWorkOrder()
        {
            this.Db_BaseWorkOrderTaskUser = new HashSet<Db_BaseWorkOrderTaskUser>();
            this.Db_BaseWorkOrderApprovalHistory = new HashSet<Db_BaseWorkOrderApprovalHistory>();
        }
    
        public string Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public byte OrderType { get; set; }
        public byte OrderStatus { get; set; }
        public string WorkFlowDefinitionId { get; set; }
        public string WorkFlowBookMarkId { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_BaseWorkOrderTaskUser> Db_BaseWorkOrderTaskUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_BaseWorkOrderApprovalHistory> Db_BaseWorkOrderApprovalHistory { get; set; }
    }
}
