//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_WorkFlowDefLine
    {
        public string Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<double> M { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Db_WorkFlowDefinitionId { get; set; }
    
        public virtual Db_WorkFlowDefinition Db_WorkFlowDefinition { get; set; }
    }
}
