//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace monkey.service.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_WorkFlowDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Db_WorkFlowDefinition()
        {
            this.Db_WorkFlowDefArea = new HashSet<Db_WorkFlowDefArea>();
            this.Db_WorkFlowDefLine = new HashSet<Db_WorkFlowDefLine>();
            this.Db_WorkFlowDefStep = new HashSet<Db_WorkFlowDefStep>();
        }
    
        public string Id { get; set; }
        public string Caption { get; set; }
        public string Descript { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_WorkFlowDefArea> Db_WorkFlowDefArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_WorkFlowDefLine> Db_WorkFlowDefLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Db_WorkFlowDefStep> Db_WorkFlowDefStep { get; set; }
    }
}
